# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b0f573fdaad67c6732a0565d612dc35"
name = "app-test-section"
handle = "app-test-section"
application_url = "https://lips-galleries-incorporated-output.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reedjoker.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lips-galleries-incorporated-output.trycloudflare.com/auth/callback",
  "https://lips-galleries-incorporated-output.trycloudflare.com/auth/shopify/callback",
  "https://lips-galleries-incorporated-output.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
